export interface ServiceContent {
  slug: string
  headline: string
  highlightWord: string
  heroDescription: string
  painTitle: string
  painText: string
  painPoints: string[]
  benefitTitle: string
  benefitText: string
  benefits: string[]
  objectionTitle: string
  objectionText: string
  ctaText: string
  badgeType: 'associado' | 'exclusivo' | 'certificado'
  badgeText: string
  faqItems: { q: string; a: string }[]
}

export const SERVICE_CONTENT: Record<string, ServiceContent> = {
  'treinamentos-e-qualificacoes-profissionais': {
    slug: 'treinamentos-e-qualificacoes-profissionais',
    headline: 'Treinamentos e qualificações',
    highlightWord: 'profissionais',
    heroDescription: 'Capacite sua equipe com treinamentos práticos e certificados reconhecidos no mercado da beleza em Uberlândia.',
    painTitle: 'Sua equipe está ficando para trás?',
    painText: 'O mercado da beleza evolui rápido. Novas técnicas, novos produtos, novas exigências dos clientes. Uma equipe desatualizada perde clientes para a concorrência e compromete o faturamento do salão.',
    painPoints: [
      'Clientes reclamando da qualidade dos serviços',
      'Equipe sem domínio das técnicas mais procuradas',
      'Dificuldade para reter profissionais qualificados',
      'Perda de clientes para concorrentes mais atualizados',
    ],
    benefitTitle: 'Treinamentos que geram resultado',
    benefitText: 'O Sindibes oferece treinamentos desenvolvidos por instrutores com experiência real em salões de Uberlândia. Cada programa é pensado para resolver problemas concretos do dia a dia e gerar retorno mensurável.',
    benefits: [
      'Certificação reconhecida pelo mercado',
      'Instrutores com experiência prática em salões',
      'Turmas reduzidas para atenção individual',
      'Conteúdo atualizado com as tendências do setor',
      'Material didático incluso',
      'Acompanhamento pós-treinamento',
    ],
    objectionTitle: 'Quanto custa NÃO qualificar?',
    objectionText: 'Muitos donos de salão adiam a qualificação por preocupação com o custo. Mas os números mostram que a falta de treinamento custa muito mais: clientes perdidos, retrabalho, rotatividade de equipe e multas por irregularidades. Com o Sindibes, o investimento tem condições exclusivas para associados.',
    ctaText: 'Quero qualificar minha equipe',
    badgeType: 'certificado',
    badgeText: 'Certificação reconhecida',
    faqItems: [
      { q: 'Quais treinamentos estão disponíveis?', a: 'Oferecemos treinamentos em técnicas de corte, coloração, gestão financeira, gestão de pessoas, atendimento ao cliente, marketing digital para salões e regularização profissional.' },
      { q: 'Os treinamentos são presenciais?', a: 'Sim, a maioria é presencial em Uberlândia, permitindo prática supervisionada. Também oferecemos módulos online complementares.' },
      { q: 'Recebo certificado?', a: 'Sim, todos os treinamentos emitem certificado reconhecido com carga horária especificada.' },
    ],
  },
  'assessoria-juridica-e-contabil-para-empresas-da-be': {
    slug: 'assessoria-juridica-e-contabil-para-empresas-da-be',
    headline: 'Assessoria jurídica e contábil',
    highlightWord: 'especializada',
    heroDescription: 'Proteja seu negócio da beleza com assessoria jurídica e contábil especializada no setor, em Uberlândia.',
    painTitle: 'Seu salão está protegido juridicamente?',
    painText: 'Processos trabalhistas, problemas fiscais e irregularidades podem fechar as portas do seu salão de um dia para o outro. A maioria dos donos de salão só procura ajuda jurídica quando o problema já existe.',
    painPoints: [
      'Risco de processos trabalhistas por vínculos informais',
      'Multas por irregularidades fiscais e sanitárias',
      'Contratos mal feitos com profissionais e fornecedores',
      'Impostos pagos a mais por falta de planejamento tributário',
    ],
    benefitTitle: 'Prevenção custa menos que correção',
    benefitText: 'A assessoria do Sindibes é preventiva: identificamos riscos antes que virem problemas. Nossa equipe de advogados e contadores conhece as especificidades do setor da beleza e oferece orientação personalizada.',
    benefits: [
      'Advogados especializados em direito trabalhista do setor',
      'Contadores com experiência em salões e clínicas',
      'Consultoria preventiva mensal',
      'Apoio em processos trabalhistas e fiscais',
      'Planejamento tributário para pagar menos impostos',
      'Regularização completa da empresa',
    ],
    objectionTitle: 'Assessoria acessível para todos os portes',
    objectionText: 'Muitos empresários acham que assessoria especializada é cara demais. No Sindibes, os associados têm acesso a assessoria jurídica e contábil com valores muito abaixo do mercado, viabilizando para salões de todos os tamanhos.',
    ctaText: 'Quero proteger meu negócio',
    badgeType: 'exclusivo',
    badgeText: 'Valores exclusivos para associados',
    faqItems: [
      { q: 'A assessoria inclui processos trabalhistas?', a: 'Sim, nossos advogados acompanham processos trabalhistas existentes e atuam na prevenção de novos, orientando sobre vínculos e contratos.' },
      { q: 'Posso trocar meu contador pelo do Sindibes?', a: 'Sim, nossa contabilidade é especializada no setor da beleza e pode assumir a escrituração completa da sua empresa.' },
      { q: 'Como funciona o atendimento?', a: 'Você tem acesso a consultas presenciais, por telefone e WhatsApp, com horários flexíveis para não impactar sua rotina.' },
    ],
  },
  'beneficios-para-associados': {
    slug: 'beneficios-para-associados',
    headline: 'Benefícios exclusivos para',
    highlightWord: 'associados',
    heroDescription: 'Planos de saúde, odontológico, crédito e muito mais com condições que só o Sindibes oferece em Uberlândia.',
    painTitle: 'Você está pagando caro demais?',
    painText: 'Profissionais e donos de salão pagam valores altíssimos em planos de saúde, odontológico e serviços essenciais. Sem poder de negociação coletiva, cada um fica à mercê dos preços de mercado.',
    painPoints: [
      'Planos de saúde individuais com preços proibitivos',
      'Sem acesso a crédito com juros razoáveis',
      'Assessoria jurídica e contábil caríssima',
      'Nenhum suporte ou orientação especializada',
    ],
    benefitTitle: 'O poder da negociação coletiva',
    benefitText: 'O Sindibes negocia coletivamente com operadoras, bancos e prestadores de serviço, garantindo condições que nenhum profissional conseguiria sozinho. Todos os benefícios estão inclusos na associação.',
    benefits: [
      'Plano de saúde com desconto significativo',
      'Plano odontológico com cobertura ampla',
      'Acesso a crédito com juros reduzidos',
      'Assessoria jurídica e contábil inclusa',
      'Treinamentos com preços especiais',
      'Rede de networking com outros profissionais',
    ],
    objectionTitle: 'A associação se paga no primeiro mês',
    objectionText: 'Comparando o valor da associação com a economia nos benefícios, a maioria dos associados recupera o investimento já no primeiro mês. É uma conta que fecha: compare o valor do plano de saúde individual com o que oferecemos.',
    ctaText: 'Quero ser associado',
    badgeType: 'exclusivo',
    badgeText: 'Economia real para associados',
    faqItems: [
      { q: 'Quanto custa a associação?', a: 'Entre em contato para conhecer os valores atualizados. Temos planos para profissionais autônomos e para empresas.' },
      { q: 'Meus funcionários também podem usar?', a: 'Sim, empresas associadas podem estender os benefícios para toda a equipe com condições especiais.' },
      { q: 'Posso cancelar quando quiser?', a: 'Não há fidelidade mínima. Você permanece associado enquanto os benefícios fizerem sentido para você.' },
    ],
  },
  'plano-de-saude': {
    slug: 'plano-de-saude',
    headline: 'Plano de Saúde para',
    highlightWord: 'profissionais da beleza',
    heroDescription: 'Cuide da saúde da sua equipe com planos negociados coletivamente pelo Sindibes, com valores muito abaixo do mercado.',
    painTitle: 'Saúde não pode esperar',
    painText: 'Profissionais da beleza trabalham de pé, com movimentos repetitivos e exposição a produtos químicos. Sem plano de saúde, qualquer problema vira uma emergência financeira que pode afastar você do trabalho por semanas.',
    painPoints: [
      'Consultas e exames particulares com custo elevado',
      'Filas intermináveis no SUS para procedimentos simples',
      'Afastamento do trabalho sem cobertura',
      'Doenças ocupacionais sem acompanhamento',
    ],
    benefitTitle: 'Planos negociados pelo sindicato',
    benefitText: 'O Sindibes negocia diretamente com as operadoras de saúde, conseguindo tabelas que seriam impossíveis para contratações individuais. Cobertura ampla, rede credenciada em Uberlândia e região.',
    benefits: [
      'Valores até 40% menores que planos individuais',
      'Rede credenciada completa em Uberlândia',
      'Cobertura para consultas, exames e internações',
      'Extensível para dependentes',
      'Sem carência para casos específicos',
      'Acompanhamento de saúde ocupacional',
    ],
    objectionTitle: 'Investimento na saúde é investimento no negócio',
    objectionText: 'Um profissional afastado por problemas de saúde custa muito mais do que a mensalidade do plano. Oferecer plano de saúde também ajuda a reter os melhores profissionais na sua equipe.',
    ctaText: 'Quero cotar meu plano',
    badgeType: 'associado',
    badgeText: 'Exclusivo para associados',
    faqItems: [
      { q: 'Quais operadoras estão disponíveis?', a: 'Trabalhamos com as principais operadoras de Uberlândia. Entre em contato para conhecer as opções atuais.' },
      { q: 'Tem carência?', a: 'Depende do plano e da operadora. Em muitos casos, conseguimos condições de carência reduzida ou zero para associados.' },
      { q: 'Posso incluir minha família?', a: 'Sim, os planos permitem inclusão de dependentes com as mesmas condições negociadas.' },
    ],
  },
  'qualificacao-em-gestao-financeira': {
    slug: 'qualificacao-em-gestao-financeira',
    headline: 'Qualificação em gestão',
    highlightWord: 'financeira',
    heroDescription: 'Aprenda a controlar as finanças do seu salão e transformar faturamento em lucro real, com orientação prática.',
    painTitle: 'Seu salão fatura, mas não sobra?',
    painText: 'Esse é o problema mais comum entre donos de salão: o dinheiro entra, mas nunca sobra. Sem controle financeiro, é impossível saber se o negócio é realmente lucrativo ou se está caminhando para um colapso.',
    painPoints: [
      'Mistura entre contas pessoais e do salão',
      'Precificação baseada em achismo',
      'Sem controle de fluxo de caixa',
      'Impostos pagos sem planejamento',
    ],
    benefitTitle: 'Finanças organizadas, lucro real',
    benefitText: 'Nossa qualificação em gestão financeira é 100% prática e voltada para a realidade de salões e clínicas de estética. Você sai com um plano financeiro montado para o seu negócio.',
    benefits: [
      'Precificação correta dos serviços',
      'Controle de fluxo de caixa simplificado',
      'Separação de finanças pessoais e empresariais',
      'Planejamento tributário básico',
      'Análise de rentabilidade por serviço',
      'Planilhas prontas para usar no dia a dia',
    ],
    objectionTitle: 'Gestão financeira não é complicada',
    objectionText: 'Muitos donos de salão evitam olhar para os números por achar que é complicado. Nosso treinamento simplifica tudo: ferramentas simples, linguagem acessível e aplicação imediata. Se você sabe fazer uma conta no celular, consegue gerir suas finanças.',
    ctaText: 'Quero organizar minhas finanças',
    badgeType: 'certificado',
    badgeText: 'Certificação em gestão financeira',
    faqItems: [
      { q: 'Preciso ter experiência com finanças?', a: 'Não. O treinamento começa do básico e avança gradualmente. É pensado para quem nunca teve formação na área.' },
      { q: 'O treinamento é individual ou em grupo?', a: 'Turmas reduzidas para permitir acompanhamento individual da realidade de cada negócio.' },
      { q: 'Vou receber material de apoio?', a: 'Sim, planilhas, modelos e guias práticos que você pode usar imediatamente no seu salão.' },
    ],
  },
  'qualificacao-em-gestao-de-pessoas': {
    slug: 'qualificacao-em-gestao-de-pessoas',
    headline: 'Qualificação em gestão de',
    highlightWord: 'pessoas',
    heroDescription: 'Lidere sua equipe com confiança. Aprenda a contratar, reter e desenvolver profissionais da beleza.',
    painTitle: 'Sua equipe é sua maior dor de cabeça?',
    painText: 'Rotatividade alta, conflitos internos, profissionais desmotivados, falta de comprometimento. Se você identificou algum desses problemas, está na hora de investir em gestão de pessoas.',
    painPoints: [
      'Alta rotatividade de profissionais',
      'Conflitos entre membros da equipe',
      'Dificuldade para encontrar bons profissionais',
      'Falta de comprometimento da equipe com resultados',
    ],
    benefitTitle: 'Liderança que retém talentos',
    benefitText: 'Aprenda técnicas de gestão de pessoas adaptadas para o ambiente de salão. Da contratação à retenção, do feedback à motivação, tudo com exemplos reais do setor.',
    benefits: [
      'Processos de recrutamento e seleção eficientes',
      'Técnicas de feedback e comunicação',
      'Programas de incentivo que funcionam em salões',
      'Gestão de conflitos no ambiente de trabalho',
      'Como montar comissionamento justo',
      'Liderança situacional para donos de salão',
    ],
    objectionTitle: 'Liderar se aprende',
    objectionText: 'A maioria dos donos de salão aprendeu a arte da beleza, não a arte de liderar. E tudo bem: liderança é uma habilidade que se desenvolve. Com as ferramentas certas, você transforma sua equipe no maior diferencial do seu negócio.',
    ctaText: 'Quero melhorar minha equipe',
    badgeType: 'certificado',
    badgeText: 'Certificação em gestão de pessoas',
    faqItems: [
      { q: 'O treinamento ajuda com problemas específicos?', a: 'Sim, parte do programa é dedicada a resolver situações reais trazidas pelos participantes.' },
      { q: 'Posso enviar meu gerente no meu lugar?', a: 'Claro! O programa é ideal tanto para donos quanto para gestores e coordenadores de equipe.' },
      { q: 'Quanto tempo dura?', a: 'O programa é modular, com encontros semanais. A duração depende do nível de aprofundamento escolhido.' },
    ],
  },
  'planejamento-empresarial-para-empresas-da-beleza': {
    slug: 'planejamento-empresarial-para-empresas-da-beleza',
    headline: 'Planejamento empresarial para',
    highlightWord: 'empresas da beleza',
    heroDescription: 'Transforme seu salão em uma empresa organizada e lucrativa com planejamento estratégico personalizado.',
    painTitle: 'Seu salão funciona no improviso?',
    painText: 'Sem planejamento, cada mês é uma surpresa. Bons meses passam sem capitalizar, meses ruins viram crises. A maioria dos salões que fecham tinha faturamento suficiente: o que faltava era planejamento.',
    painPoints: [
      'Decisões baseadas em intuição, não em dados',
      'Sem metas claras de faturamento e crescimento',
      'Gastos descontrolados e investimentos mal direcionados',
      'Falta de visão de longo prazo para o negócio',
    ],
    benefitTitle: 'Planejamento que funciona no salão',
    benefitText: 'Nosso programa de planejamento empresarial é feito para a realidade do setor da beleza. Você sai com um plano de ação concreto: metas, orçamento, cronograma e indicadores para acompanhar.',
    benefits: [
      'Diagnóstico completo do seu negócio',
      'Definição de metas realistas e mensuráveis',
      'Plano de ação com cronograma',
      'Indicadores de desempenho (KPIs) para salões',
      'Estratégias de crescimento sustentável',
      'Acompanhamento mensal dos resultados',
    ],
    objectionTitle: 'Planejamento não é burocracia',
    objectionText: 'Planejamento empresarial não significa preencher formulários e criar documentos que ninguém lê. No nosso programa, tudo é visual, prático e acompanhado. Você implementa enquanto aprende.',
    ctaText: 'Quero planejar meu crescimento',
    badgeType: 'exclusivo',
    badgeText: 'Programa exclusivo Sindibes',
    faqItems: [
      { q: 'Funciona para salões pequenos?', a: 'Sim, o programa é adaptável para qualquer porte, de profissional autônomo a salões com dezenas de funcionários.' },
      { q: 'Inclui acompanhamento após o programa?', a: 'Sim, oferecemos acompanhamento mensal para ajudar na execução do plano criado.' },
      { q: 'Preciso parar o salão para participar?', a: 'Não, os encontros são organizados para não conflitar com os horários de pico dos salões.' },
    ],
  },
  'plano-odontologico': {
    slug: 'plano-odontologico',
    headline: 'Plano Odontológico para',
    highlightWord: 'profissionais da beleza',
    heroDescription: 'O sorriso é ferramenta de trabalho no setor da beleza. Cuide dele com planos odontológicos acessíveis negociados pelo Sindibes.',
    painTitle: 'Tratamento odontológico particular é caro',
    painText: 'Um tratamento de canal, uma coroa, uma limpeza regular: custos que se acumulam e afastam muitos profissionais do cuidado básico com a saúde bucal. E no setor da beleza, o sorriso é cartão de visitas.',
    painPoints: [
      'Custos altos para tratamentos particulares',
      'Cobertura limitada nos planos mais baratos',
      'Rede credenciada insuficiente em Uberlândia',
      'Profissionais evitando ir ao dentista pelo custo',
    ],
    benefitTitle: 'Sorriso cuidado, atendimento confiante',
    benefitText: 'O Sindibes negocia com operadoras odontológicas para garantir cobertura ampla e preços acessíveis. Consultas, limpezas, restaurações e muito mais sem pesar no orçamento.',
    benefits: [
      'Consultas e limpezas periódicas cobertas',
      'Restaurações e tratamentos de canal',
      'Rede credenciada em Uberlândia e região',
      'Extensível para dependentes',
      'Valores até 50% menores que planos individuais',
      'Sem burocracia para utilizar',
    ],
    objectionTitle: 'Prevenção sai muito mais barato',
    objectionText: 'Um plano odontológico permite que você faça consultas preventivas regulares, evitando tratamentos caros e emergenciais. O custo mensal é menor que uma única consulta particular.',
    ctaText: 'Quero cotar meu plano',
    badgeType: 'associado',
    badgeText: 'Exclusivo para associados',
    faqItems: [
      { q: 'Cobre ortodontia?', a: 'Depende do plano escolhido. Temos opções com e sem cobertura ortodôntica. Consulte as opções disponíveis.' },
      { q: 'Tem dentista perto do meu salão?', a: 'Nossa rede credenciada cobre diversas regiões de Uberlândia. Consulte a disponibilidade para sua área.' },
      { q: 'Posso usar no mesmo mês da adesão?', a: 'Para a maioria dos procedimentos básicos, sim. Procedimentos mais complexos podem ter carência.' },
    ],
  },
  'regularizacao-e-certificacao-profissional': {
    slug: 'regularizacao-e-certificacao-profissional',
    headline: 'Regularização e Certificação',
    highlightWord: 'Profissional',
    heroDescription: 'Regularize sua empresa e certificações profissionais com o apoio do Sindibes. Evite multas e ganhe credibilidade.',
    painTitle: 'Seu negócio está 100% regular?',
    painText: 'Fiscalização da vigilância sanitária, exigências trabalhistas, alvarás e licenças: a lista de obrigações é longa. Uma irregularidade pode gerar multas pesadas ou até o fechamento do estabelecimento.',
    painPoints: [
      'Risco de autuação por falta de alvará ou licença',
      'Profissionais sem certificação exigida',
      'Documentação desorganizada e desatualizada',
      'Desconhecimento das exigências legais do setor',
    ],
    benefitTitle: 'Regularização completa e sem estresse',
    benefitText: 'O Sindibes cuida de toda a documentação e certificação necessária para seu negócio funcionar 100% dentro da lei. Desde o alvará até a certificação individual de cada profissional.',
    benefits: [
      'Levantamento completo das pendências',
      'Orientação sobre documentação necessária',
      'Apoio na obtenção de alvarás e licenças',
      'Certificação profissional reconhecida',
      'Acompanhamento de prazos e renovações',
      'Preparação para fiscalizações',
    ],
    objectionTitle: 'Regularizar é mais simples do que parece',
    objectionText: 'Muitos empresários adiam a regularização por achar que é um processo burocrático e caro. Com o Sindibes, você tem um passo a passo claro, apoio em cada etapa e custos reduzidos para associados.',
    ctaText: 'Quero regularizar meu negócio',
    badgeType: 'certificado',
    badgeText: 'Certificação oficial',
    faqItems: [
      { q: 'Quanto tempo leva para regularizar?', a: 'Depende da situação atual. Em média, conseguimos resolver as principais pendências em 30 a 60 dias.' },
      { q: 'Vocês fazem para qualquer tipo de estabelecimento?', a: 'Sim, atendemos salões, barbearias, clínicas de estética, spas e profissionais autônomos.' },
      { q: 'As certificações são reconhecidas?', a: 'Sim, todas as certificações emitidas têm validade legal e são reconhecidas pelos órgãos competentes.' },
    ],
  },
  'acesso-de-credito': {
    slug: 'acesso-de-credito',
    headline: 'Acesso de Crédito para',
    highlightWord: 'salões e profissionais',
    heroDescription: 'Crédito com juros reduzidos e condições especiais para profissionais e empresas da beleza em Uberlândia.',
    painTitle: 'Precisa de crédito mas tem medo dos juros?',
    painText: 'Reformar o salão, comprar equipamentos, montar estoque: tudo exige investimento. Mas os juros do mercado para pequenos empresários são abusivos, e muitas vezes a burocracia impede o acesso.',
    painPoints: [
      'Juros altíssimos nos empréstimos tradicionais',
      'Burocracia excessiva nos bancos',
      'Falta de garantias exigidas pelas instituições',
      'Sem orientação para escolher a melhor opção',
    ],
    benefitTitle: 'Crédito inteligente para crescer',
    benefitText: 'O Sindibes tem parcerias com instituições financeiras que oferecem linhas de crédito especiais para o setor da beleza. Juros menores, menos burocracia e orientação para usar o crédito da melhor forma.',
    benefits: [
      'Taxas de juros reduzidas para associados',
      'Menos burocracia na aprovação',
      'Linhas de crédito específicas para o setor',
      'Orientação sobre o melhor uso do recurso',
      'Parcelamento facilitado',
      'Consultoria financeira pré-crédito',
    ],
    objectionTitle: 'Crédito certo na hora certa',
    objectionText: 'Nem todo crédito é bom. Antes de acessar qualquer linha, nossa equipe analisa sua situação e orienta sobre o momento certo e o valor ideal. Você só toma crédito quando faz sentido para o seu negócio.',
    ctaText: 'Quero conhecer as opções de crédito',
    badgeType: 'exclusivo',
    badgeText: 'Condições exclusivas Sindibes',
    faqItems: [
      { q: 'Preciso ser MEI ou ter CNPJ?', a: 'Temos opções tanto para pessoa física quanto jurídica. Profissionais autônomos também podem acessar.' },
      { q: 'Qual o valor mínimo e máximo?', a: 'As linhas de crédito variam. Entre em contato para uma análise personalizada da sua necessidade.' },
      { q: 'Quanto tempo demora para aprovação?', a: 'Com a documentação em dia, a aprovação pode sair em poucos dias úteis, dependendo da instituição parceira.' },
    ],
  },
}
